name: Playwright Tests
on:
  workflow_call:
    inputs:
      branch-name:
        description: "The branch name to test"
        required: true
        type: string
    outputs:
      e2e-outcome:
        description: "E2E tests outcome, one of 'success', 'failure', 'skipped', 'cancelled'"
        value: ${{ jobs.test.outputs.e2e-outcome }}
      e2e-summary:
        description: "E2E summary in markdown format"
        value: ${{ jobs.test.outputs.e2e-summary }}
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  test:
    outputs:
      e2e-outcome: ${{ steps.run-e2e.outcome }}
      e2e-summary: ${{ steps.analyze-e2e-report.outputs.summary }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch-name }}

      - id: get-update-vars
        run: |
          HEAD_SHA=$(git rev-parse HEAD)
          OWNER=$(echo $GITHUB_REPOSITORY | awk -F'/' '{print $1}')
          REPOSITORY=$(echo $GITHUB_REPOSITORY | awk -F'/' '{print $2}')

          echo "head-sha=$HEAD_SHA" >> "$GITHUB_OUTPUT"
          echo "owner=$OWNER" >> "$GITHUB_OUTPUT"
          echo "repository=$REPOSITORY" >> "$GITHUB_OUTPUT"

      - uses: launchbynttdata/e2e-workflow-trigger-demo/.github/actions/update-e2e-status-check@main
        with:
          state: in_progress
          context: E2E
          description: E2E tests running
          sha: ${{ steps.get-update-vars.outputs.head-sha }}
          owner: ${{ steps.get-update-vars.outputs.owner }}
          repo: ${{ steps.get-update-vars.outputs.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Restore cached node_modules
        uses: actions/cache/restore@v5
        id: cache-node
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Restore cached Playwright browsers
        uses: actions/cache/restore@v5
        id: cache-playwright
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright_browsers-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Cache node_modules
        uses: actions/cache/save@v5
        id: save-node-cache
        if: ${{ steps.cache-node.outputs.cache-hit != 'true' }}
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Cache Playwright browsers
        uses: actions/cache/save@v5
        id: save-playwright-cache
        if: ${{ steps.cache-playwright.outputs.cache-hit != 'true' }}
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright_browsers-${{ hashFiles('package-lock.json') }}

      - id: run-e2e
        name: Run Playwright tests
        run: npm run e2e

      - id: upload-artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - id: analyze-e2e-report
        uses: daun/playwright-report-summary@v3
        if: ${{ !cancelled() }}
        with:
          report-file: playwright-report/test-results.json
          report-url: "${{ steps.upload-artifact.outputs.artifact-url }}"
          create-comment: false
