name: Playwright Tests
on:
  workflow_call:
    inputs:
      branch-name:
        description: "The branch name to test"
        required: true
        type: string
    outputs:
      e2e-outcome:
        description: "E2E tests outcome, one of 'success', 'failure', 'skipped', 'cancelled'"
        value: ${{ jobs.test.outputs.e2e-outcome }}
      e2e-summary:
        description: "E2E summary in markdown format"
        value: ${{ jobs.test.outputs.e2e-summary }}
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  actions: write

jobs:
  test:
    name: Run E2E Tests
    outputs:
      e2e-outcome: ${{ steps.run-e2e.outcome }}
      e2e-summary: ${{ steps.analyze-e2e-report.outputs.summary }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      # Need to figure out how to drive this tag based on package.json version
      image: mcr.microsoft.com/playwright:v1.57.0-noble
    steps:
      - id: prereqs
        name: Install GH CLI
        shell: bash
        run: |
          # Install GH CLI
          (type -p wget >/dev/null || (apt update && apt install wget -y)) \
          && mkdir -p -m 755 /etc/apt/keyrings \
          && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && mkdir -p -m 755 /etc/apt/sources.list.d \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt update \
          && apt install gh -y

          # Fix "dubious ownership" errors in container
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - id: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch-name }}

      - id: determine-event-source
        name: Determine Event Source
        shell: bash
        run: |
          if [[ "${{ github.event.workflow }}" == ".github/workflows/playwright.yml" ]]; then
            echo "source=workflow_dispatch" >> "$GITHUB_OUTPUT"
          else
            echo "source=workflow_call" >> "$GITHUB_OUTPUT"
          fi

      - id: get-update-vars
        name: Gather variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          HEAD_SHA=$(git rev-parse HEAD)
          OWNER=$(echo $GITHUB_REPOSITORY | awk -F'/' '{print $1}')
          REPOSITORY=$(echo $GITHUB_REPOSITORY | awk -F'/' '{print $2}')
          TARGET_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

          if [[ "${{ steps.determine-event-source.outputs.source }}" == "workflow_call" ]]; then
            PR_NUMBER=$(gh pr view "${{ github.event.issue.pull_request.html_url }}" --json number --jq .number)
            echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
          fi

          echo "head-sha=$HEAD_SHA" >> "$GITHUB_OUTPUT"
          echo "owner=$OWNER" >> "$GITHUB_OUTPUT"
          echo "repository=$REPOSITORY" >> "$GITHUB_OUTPUT"
          echo "target-url=$TARGET_URL" >> "$GITHUB_OUTPUT"

      - id: placeholder-comment
        name: Create placeholder comment
        # Don't try to create a comment when the workflow is manually triggered through the UI
        if: steps.determine-event-source.outputs.source == 'workflow_call'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          cat <<EOC > e2e_comment.md
          > [!IMPORTANT]
          > E2E test run has been triggered!

          This comment will be updated with the outcome once the job completes.
          EOC

          # Delete the existing comment, if there is one
          gh pr comment "${{ steps.get-update-vars.outputs.pr-number }}" --delete-last --yes || true
          gh pr comment "${{ steps.get-update-vars.outputs.pr-number }}" --body-file e2e_comment.md

      - id: update-status-check-pending
        name: Set E2E Check URL
        uses: launchbynttdata/e2e-workflow-trigger-demo/.github/actions/update-e2e-status-check@main
        with:
          state: pending
          context: E2E Tests
          description: E2E tests running
          sha: ${{ steps.get-update-vars.outputs.head-sha }}
          owner: ${{ steps.get-update-vars.outputs.owner }}
          repo: ${{ steps.get-update-vars.outputs.repository }}
          target_url: ${{ steps.get-update-vars.outputs.target-url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Restore cached node_modules
        uses: actions/cache/restore@v5
        id: cache-node
        with:
          path: ./node_modules
          key: ${{ runner.os }}-test-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache-node.outputs.cache-hit != 'true' }}
        shell: bash
        run: npm ci

      - name: Install Playwright Browsers
        shell: bash
        run: npx playwright install --with-deps

      - name: Cache node_modules
        uses: actions/cache/save@v5
        id: save-node-cache
        if: ${{ steps.cache-node.outputs.cache-hit != 'true' }}
        with:
          path: node_modules
          key: ${{ runner.os }}-test-node_modules-${{ hashFiles('package-lock.json') }}

      - id: run-e2e
        name: Run Playwright tests
        env:
          HOME: /root
        shell: bash
        run: npm run e2e
        continue-on-error: true

      - id: upload-artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - id: analyze-e2e-report
        # Will need to be explicitly approved by CMM Security
        uses: daun/playwright-report-summary@v3
        if: ${{ !cancelled() }}
        with:
          report-file: playwright-report/test-results.json
          report-url: "${{ steps.upload-artifact.outputs.artifact-url }}"
          create-comment: false

      - name: Write testing outcome comment
        if: ${{ !cancelled() && steps.determine-event-source.outputs.source == 'workflow_call'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          echo "${{ steps.analyze-e2e-report.outputs.summary }}" > e2e_comment.md
          gh pr comment "${{ steps.get-update-vars.outputs.pr-number }}" --create-if-none --edit-last --body-file e2e_comment.md

      - id: update-status-check-complete
        if: ${{ always() }}
        name: Update Status
        uses: launchbynttdata/e2e-workflow-trigger-demo/.github/actions/update-e2e-status-check@main
        with:
          state: ${{ steps.run-e2e.outcome }}
          description: E2E tests completed - ${{ steps.run-e2e.outcome }}
          context: E2E Tests
          sha: ${{ steps.get-update-vars.outputs.head-sha }}
          owner: ${{ steps.get-update-vars.outputs.owner }}
          repo: ${{ steps.get-update-vars.outputs.repository }}
          target_url: ${{ steps.get-update-vars.outputs.target-url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
