on:
  issue_comment:
    types: [created]

permissions:
  checks: write
  statuses: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  get-comment-branch:
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test e2e') }}
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.get-pr-details.outputs.branch-name }}
      head-sha: ${{ steps.get-pr-details.outputs.head-sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Retrieve PR details
        id: get-pr-details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(gh pr view "${{ github.event.issue.pull_request.html_url }}" --json headRefName --jq .headRefName)
          SHA=$(gh pr view "${{ github.event.issue.pull_request.html_url }}" --json headRefOid --jq .headRefOid)
          echo "branch-name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
          echo "head-sha=$SHA" >> "$GITHUB_OUTPUT"

      - name: React to comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "rocket"

  call-e2e-workflow:
    if: ${{ github.event.issue.pull_request }}
    uses: launchbynttdata/e2e-workflow-trigger-demo/.github/workflows/playwright.yml@main
    needs: [get-comment-branch]
    with:
      branch-name: ${{ needs.get-comment-branch.outputs.branch-name }}

  update-status-check-success:
    permissions:
      checks: write
      statuses: write
      contents: read
    needs: [get-comment-branch, call-e2e-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Update Status Check
        uses: launchbynttdata/e2e-workflow-trigger-demo/.github/actions/update-e2e-status-check@main
        with:
          success: ${{ needs.call-e2e-workflow.outputs.e2e-outcome == 'success' }}
          repo: e2e-workflow-trigger-demo
          owner: launchbynttdata
          sha: ${{ needs.get-comment-branch.outputs.head-sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
