on: pull_request

permissions:
  contents: write
  checks: write
  statuses: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: get-update-vars
        run: |
          OWNER=$(echo $GITHUB_REPOSITORY | awk -F'/' '{print $1}')
          REPOSITORY=$(echo $GITHUB_REPOSITORY | awk -F'/' '{print $1}')

          echo "owner=$OWNER" >> "$GITHUB_OUTPUT"
          echo "repository=$REPOSITORY" >> "$GITHUB_OUTPUT"

      - uses: launchbynttdata/e2e-workflow-trigger-demo/.github/actions/update-e2e-status-check@main
        with:
          state: requested
          context: E2E
          description: "Comment '/e2e test' to run"
          sha: ${{ github.event.pull_request.head.sha }}
          owner: ${{ steps.get-update-vars.outputs.owner }}
          repo: ${{ steps.get-update-vars.outputs.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Restore cached node_modules
        uses: actions/cache/restore@v5
        id: cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Cache node_modules
        uses: actions/cache/save@v5
        id: save-cache
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Lint code
        run: npm run lint
