on:
  issue_comment:
    types: [created]

jobs:
  get-comment-branch:
    permissions:
      pull-requests: read
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/test e2e') }}
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.get-branch-name.outputs.branch-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Retrieve branch name for pull request
        id: get-branch-name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(gh pr view "${{ github.event.issue.pull_request.url }}" --json headRefName --jq .headRefName)
          echo "branch-name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

  call-e2e-workflow:
    permissions:
      actions: write
    if: ${{ github.event.issue.pull_request }}
    uses: launchbynttdata/e2e-workflow-trigger-demo/.github/workflows/playwright.yml@main
    needs: [get-comment-branch]
    with:
      branch-name: ${{ needs.get-comment-branch.outputs.branch-name }}
